[project]
name = "repl-nix-infotheoryinpython"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "plotly>=5.24.1",
    "streamlit>=1.40.2",
]
